### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by sebschlicht** [alexandrequaresma/rpi-keycloak#1]
Hey alexandrequaresma ,

first of all, thanks for your effort on making Keycloak available on Pi.
It was not without joy that I spotted your image and had to try it out immediately.

However, when running your Keycloak image on my Raspberry Pi 4 via

    docker run --name keycloak -d -p 8180:8080 -p 9990:9990 aquaresma/rpi-keycloak:12.0.4

I get the following error message in the docker logs and the container enters a restart loop:

    standard_init_linux.go:207: exec user process caused "exec format error"

Apparently, this is a not too uncommon error on ARM devices but my brief search did not yield any real leads.

Any ideas on what might cause this issue and how to fix it?

**Comment by alexandrequaresma** [comment]
Hey could you share some more details please? I think I remember having an error similar to that one while trying to run it on the wrong architecture.
If it helps, I am also using a RPI4, I am running it on k3s using Raspberry Pi OS 64 bit.

**Comment by sebschlicht** [comment]
I just set up k3s on my Pi4 running the 64-bit Ubuntu server 20.04 to try this out.
I haven't exactly figured out how to reach the application inside the pod yet but it looks like Keycloak is running just fine.
Thanks you for this hint!

**Comment by sebschlicht** [comment]
For the record: Trying to run the image on the Pi4 running a 32-bit Debian led to the error message above.

I didn't know that I wouldn't be able to run an arm64 image on the Pi4 when using a 32-bit OS, even though the numbers suggest it already.
